// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: crypto.proto

package crypto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadEvalKeysRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TenantId        string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CompiledModelId string                 `protobuf:"bytes,2,opt,name=compiled_model_id,json=compiledModelId,proto3" json:"compiled_model_id,omitempty"`
	EvalKeys        []byte                 `protobuf:"bytes,3,opt,name=eval_keys,json=evalKeys,proto3" json:"eval_keys,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UploadEvalKeysRequest) Reset() {
	*x = UploadEvalKeysRequest{}
	mi := &file_crypto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadEvalKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadEvalKeysRequest) ProtoMessage() {}

func (x *UploadEvalKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadEvalKeysRequest.ProtoReflect.Descriptor instead.
func (*UploadEvalKeysRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{0}
}

func (x *UploadEvalKeysRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UploadEvalKeysRequest) GetCompiledModelId() string {
	if x != nil {
		return x.CompiledModelId
	}
	return ""
}

func (x *UploadEvalKeysRequest) GetEvalKeys() []byte {
	if x != nil {
		return x.EvalKeys
	}
	return nil
}

type UploadEvalKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadEvalKeysResponse) Reset() {
	*x = UploadEvalKeysResponse{}
	mi := &file_crypto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadEvalKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadEvalKeysResponse) ProtoMessage() {}

func (x *UploadEvalKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadEvalKeysResponse.ProtoReflect.Descriptor instead.
func (*UploadEvalKeysResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{1}
}

func (x *UploadEvalKeysResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetEvalKeysRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TenantId        string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CompiledModelId string                 `protobuf:"bytes,2,opt,name=compiled_model_id,json=compiledModelId,proto3" json:"compiled_model_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetEvalKeysRequest) Reset() {
	*x = GetEvalKeysRequest{}
	mi := &file_crypto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEvalKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEvalKeysRequest) ProtoMessage() {}

func (x *GetEvalKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEvalKeysRequest.ProtoReflect.Descriptor instead.
func (*GetEvalKeysRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{2}
}

func (x *GetEvalKeysRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetEvalKeysRequest) GetCompiledModelId() string {
	if x != nil {
		return x.CompiledModelId
	}
	return ""
}

type GetEvalKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EvalKeys      []byte                 `protobuf:"bytes,1,opt,name=eval_keys,json=evalKeys,proto3" json:"eval_keys,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEvalKeysResponse) Reset() {
	*x = GetEvalKeysResponse{}
	mi := &file_crypto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEvalKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEvalKeysResponse) ProtoMessage() {}

func (x *GetEvalKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEvalKeysResponse.ProtoReflect.Descriptor instead.
func (*GetEvalKeysResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{3}
}

func (x *GetEvalKeysResponse) GetEvalKeys() []byte {
	if x != nil {
		return x.EvalKeys
	}
	return nil
}

func (x *GetEvalKeysResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type RotateKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ModelId       string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateKeysRequest) Reset() {
	*x = RotateKeysRequest{}
	mi := &file_crypto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateKeysRequest) ProtoMessage() {}

func (x *RotateKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateKeysRequest.ProtoReflect.Descriptor instead.
func (*RotateKeysRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{4}
}

func (x *RotateKeysRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RotateKeysRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

type RotateKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateKeysResponse) Reset() {
	*x = RotateKeysResponse{}
	mi := &file_crypto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateKeysResponse) ProtoMessage() {}

func (x *RotateKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateKeysResponse.ProtoReflect.Descriptor instead.
func (*RotateKeysResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{5}
}

func (x *RotateKeysResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RevokeKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ModelId       string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeKeysRequest) Reset() {
	*x = RevokeKeysRequest{}
	mi := &file_crypto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeKeysRequest) ProtoMessage() {}

func (x *RevokeKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeKeysRequest.ProtoReflect.Descriptor instead.
func (*RevokeKeysRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{6}
}

func (x *RevokeKeysRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RevokeKeysRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

type RevokeKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeKeysResponse) Reset() {
	*x = RevokeKeysResponse{}
	mi := &file_crypto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeKeysResponse) ProtoMessage() {}

func (x *RevokeKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeKeysResponse.ProtoReflect.Descriptor instead.
func (*RevokeKeysResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{7}
}

func (x *RevokeKeysResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_crypto_proto protoreflect.FileDescriptor

const file_crypto_proto_rawDesc = "" +
	"\n" +
	"\fcrypto.proto\x12\x06crypto\"}\n" +
	"\x15UploadEvalKeysRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12*\n" +
	"\x11compiled_model_id\x18\x02 \x01(\tR\x0fcompiledModelId\x12\x1b\n" +
	"\teval_keys\x18\x03 \x01(\fR\bevalKeys\"2\n" +
	"\x16UploadEvalKeysResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"]\n" +
	"\x12GetEvalKeysRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12*\n" +
	"\x11compiled_model_id\x18\x02 \x01(\tR\x0fcompiledModelId\"H\n" +
	"\x13GetEvalKeysResponse\x12\x1b\n" +
	"\teval_keys\x18\x01 \x01(\fR\bevalKeys\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"K\n" +
	"\x11RotateKeysRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\".\n" +
	"\x12RotateKeysResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"K\n" +
	"\x11RevokeKeysRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\".\n" +
	"\x12RevokeKeysResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xb5\x02\n" +
	"\x10CryptoKeyService\x12O\n" +
	"\x0eUploadEvalKeys\x12\x1d.crypto.UploadEvalKeysRequest\x1a\x1e.crypto.UploadEvalKeysResponse\x12F\n" +
	"\vGetEvalKeys\x12\x1a.crypto.GetEvalKeysRequest\x1a\x1b.crypto.GetEvalKeysResponse\x12C\n" +
	"\n" +
	"RotateKeys\x12\x19.crypto.RotateKeysRequest\x1a\x1a.crypto.RotateKeysResponse\x12C\n" +
	"\n" +
	"RevokeKeys\x12\x19.crypto.RevokeKeysRequest\x1a\x1a.crypto.RevokeKeysResponseB*Z(github.com/fhe-gbdt-serving/proto/cryptob\x06proto3"

var (
	file_crypto_proto_rawDescOnce sync.Once
	file_crypto_proto_rawDescData []byte
)

func file_crypto_proto_rawDescGZIP() []byte {
	file_crypto_proto_rawDescOnce.Do(func() {
		file_crypto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crypto_proto_rawDesc), len(file_crypto_proto_rawDesc)))
	})
	return file_crypto_proto_rawDescData
}

var file_crypto_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_crypto_proto_goTypes = []any{
	(*UploadEvalKeysRequest)(nil),  // 0: crypto.UploadEvalKeysRequest
	(*UploadEvalKeysResponse)(nil), // 1: crypto.UploadEvalKeysResponse
	(*GetEvalKeysRequest)(nil),     // 2: crypto.GetEvalKeysRequest
	(*GetEvalKeysResponse)(nil),    // 3: crypto.GetEvalKeysResponse
	(*RotateKeysRequest)(nil),      // 4: crypto.RotateKeysRequest
	(*RotateKeysResponse)(nil),     // 5: crypto.RotateKeysResponse
	(*RevokeKeysRequest)(nil),      // 6: crypto.RevokeKeysRequest
	(*RevokeKeysResponse)(nil),     // 7: crypto.RevokeKeysResponse
}
var file_crypto_proto_depIdxs = []int32{
	0, // 0: crypto.CryptoKeyService.UploadEvalKeys:input_type -> crypto.UploadEvalKeysRequest
	2, // 1: crypto.CryptoKeyService.GetEvalKeys:input_type -> crypto.GetEvalKeysRequest
	4, // 2: crypto.CryptoKeyService.RotateKeys:input_type -> crypto.RotateKeysRequest
	6, // 3: crypto.CryptoKeyService.RevokeKeys:input_type -> crypto.RevokeKeysRequest
	1, // 4: crypto.CryptoKeyService.UploadEvalKeys:output_type -> crypto.UploadEvalKeysResponse
	3, // 5: crypto.CryptoKeyService.GetEvalKeys:output_type -> crypto.GetEvalKeysResponse
	5, // 6: crypto.CryptoKeyService.RotateKeys:output_type -> crypto.RotateKeysResponse
	7, // 7: crypto.CryptoKeyService.RevokeKeys:output_type -> crypto.RevokeKeysResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_crypto_proto_init() }
func file_crypto_proto_init() {
	if File_crypto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crypto_proto_rawDesc), len(file_crypto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_crypto_proto_goTypes,
		DependencyIndexes: file_crypto_proto_depIdxs,
		MessageInfos:      file_crypto_proto_msgTypes,
	}.Build()
	File_crypto_proto = out.File
	file_crypto_proto_goTypes = nil
	file_crypto_proto_depIdxs = nil
}
