// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: crypto.proto

package crypto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CryptoKeyService_UploadEvalKeys_FullMethodName = "/crypto.CryptoKeyService/UploadEvalKeys"
	CryptoKeyService_GetEvalKeys_FullMethodName    = "/crypto.CryptoKeyService/GetEvalKeys"
	CryptoKeyService_RotateKeys_FullMethodName     = "/crypto.CryptoKeyService/RotateKeys"
	CryptoKeyService_RevokeKeys_FullMethodName     = "/crypto.CryptoKeyService/RevokeKeys"
)

// CryptoKeyServiceClient is the client API for CryptoKeyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CryptoKeyServiceClient interface {
	UploadEvalKeys(ctx context.Context, in *UploadEvalKeysRequest, opts ...grpc.CallOption) (*UploadEvalKeysResponse, error)
	GetEvalKeys(ctx context.Context, in *GetEvalKeysRequest, opts ...grpc.CallOption) (*GetEvalKeysResponse, error)
	RotateKeys(ctx context.Context, in *RotateKeysRequest, opts ...grpc.CallOption) (*RotateKeysResponse, error)
	RevokeKeys(ctx context.Context, in *RevokeKeysRequest, opts ...grpc.CallOption) (*RevokeKeysResponse, error)
}

type cryptoKeyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCryptoKeyServiceClient(cc grpc.ClientConnInterface) CryptoKeyServiceClient {
	return &cryptoKeyServiceClient{cc}
}

func (c *cryptoKeyServiceClient) UploadEvalKeys(ctx context.Context, in *UploadEvalKeysRequest, opts ...grpc.CallOption) (*UploadEvalKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadEvalKeysResponse)
	err := c.cc.Invoke(ctx, CryptoKeyService_UploadEvalKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoKeyServiceClient) GetEvalKeys(ctx context.Context, in *GetEvalKeysRequest, opts ...grpc.CallOption) (*GetEvalKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEvalKeysResponse)
	err := c.cc.Invoke(ctx, CryptoKeyService_GetEvalKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoKeyServiceClient) RotateKeys(ctx context.Context, in *RotateKeysRequest, opts ...grpc.CallOption) (*RotateKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateKeysResponse)
	err := c.cc.Invoke(ctx, CryptoKeyService_RotateKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoKeyServiceClient) RevokeKeys(ctx context.Context, in *RevokeKeysRequest, opts ...grpc.CallOption) (*RevokeKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeKeysResponse)
	err := c.cc.Invoke(ctx, CryptoKeyService_RevokeKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CryptoKeyServiceServer is the server API for CryptoKeyService service.
// All implementations must embed UnimplementedCryptoKeyServiceServer
// for forward compatibility.
type CryptoKeyServiceServer interface {
	UploadEvalKeys(context.Context, *UploadEvalKeysRequest) (*UploadEvalKeysResponse, error)
	GetEvalKeys(context.Context, *GetEvalKeysRequest) (*GetEvalKeysResponse, error)
	RotateKeys(context.Context, *RotateKeysRequest) (*RotateKeysResponse, error)
	RevokeKeys(context.Context, *RevokeKeysRequest) (*RevokeKeysResponse, error)
	mustEmbedUnimplementedCryptoKeyServiceServer()
}

// UnimplementedCryptoKeyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCryptoKeyServiceServer struct{}

func (UnimplementedCryptoKeyServiceServer) UploadEvalKeys(context.Context, *UploadEvalKeysRequest) (*UploadEvalKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadEvalKeys not implemented")
}
func (UnimplementedCryptoKeyServiceServer) GetEvalKeys(context.Context, *GetEvalKeysRequest) (*GetEvalKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEvalKeys not implemented")
}
func (UnimplementedCryptoKeyServiceServer) RotateKeys(context.Context, *RotateKeysRequest) (*RotateKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateKeys not implemented")
}
func (UnimplementedCryptoKeyServiceServer) RevokeKeys(context.Context, *RevokeKeysRequest) (*RevokeKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeKeys not implemented")
}
func (UnimplementedCryptoKeyServiceServer) mustEmbedUnimplementedCryptoKeyServiceServer() {}
func (UnimplementedCryptoKeyServiceServer) testEmbeddedByValue()                          {}

// UnsafeCryptoKeyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CryptoKeyServiceServer will
// result in compilation errors.
type UnsafeCryptoKeyServiceServer interface {
	mustEmbedUnimplementedCryptoKeyServiceServer()
}

func RegisterCryptoKeyServiceServer(s grpc.ServiceRegistrar, srv CryptoKeyServiceServer) {
	// If the following call panics, it indicates UnimplementedCryptoKeyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CryptoKeyService_ServiceDesc, srv)
}

func _CryptoKeyService_UploadEvalKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadEvalKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoKeyServiceServer).UploadEvalKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CryptoKeyService_UploadEvalKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoKeyServiceServer).UploadEvalKeys(ctx, req.(*UploadEvalKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CryptoKeyService_GetEvalKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEvalKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoKeyServiceServer).GetEvalKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CryptoKeyService_GetEvalKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoKeyServiceServer).GetEvalKeys(ctx, req.(*GetEvalKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CryptoKeyService_RotateKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoKeyServiceServer).RotateKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CryptoKeyService_RotateKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoKeyServiceServer).RotateKeys(ctx, req.(*RotateKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CryptoKeyService_RevokeKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoKeyServiceServer).RevokeKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CryptoKeyService_RevokeKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoKeyServiceServer).RevokeKeys(ctx, req.(*RevokeKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CryptoKeyService_ServiceDesc is the grpc.ServiceDesc for CryptoKeyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CryptoKeyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "crypto.CryptoKeyService",
	HandlerType: (*CryptoKeyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadEvalKeys",
			Handler:    _CryptoKeyService_UploadEvalKeys_Handler,
		},
		{
			MethodName: "GetEvalKeys",
			Handler:    _CryptoKeyService_GetEvalKeys_Handler,
		},
		{
			MethodName: "RotateKeys",
			Handler:    _CryptoKeyService_RotateKeys_Handler,
		},
		{
			MethodName: "RevokeKeys",
			Handler:    _CryptoKeyService_RevokeKeys_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crypto.proto",
}
