// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: control.proto

package control

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ModelName     string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	ModelContent  []byte                 `protobuf:"bytes,3,opt,name=model_content,json=modelContent,proto3" json:"model_content,omitempty"`
	LibraryType   string                 `protobuf:"bytes,4,opt,name=library_type,json=libraryType,proto3" json:"library_type,omitempty"` // xgboost | lightgbm | catboost
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterModelRequest) Reset() {
	*x = RegisterModelRequest{}
	mi := &file_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterModelRequest) ProtoMessage() {}

func (x *RegisterModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterModelRequest.ProtoReflect.Descriptor instead.
func (*RegisterModelRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterModelRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RegisterModelRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *RegisterModelRequest) GetModelContent() []byte {
	if x != nil {
		return x.ModelContent
	}
	return nil
}

func (x *RegisterModelRequest) GetLibraryType() string {
	if x != nil {
		return x.LibraryType
	}
	return ""
}

type RegisterModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterModelResponse) Reset() {
	*x = RegisterModelResponse{}
	mi := &file_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterModelResponse) ProtoMessage() {}

func (x *RegisterModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterModelResponse.ProtoReflect.Descriptor instead.
func (*RegisterModelResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterModelResponse) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

type CompileModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Profile       string                 `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"` // latency | throughput
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompileModelRequest) Reset() {
	*x = CompileModelRequest{}
	mi := &file_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileModelRequest) ProtoMessage() {}

func (x *CompileModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileModelRequest.ProtoReflect.Descriptor instead.
func (*CompileModelRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

func (x *CompileModelRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *CompileModelRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

type CompileModelResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CompiledModelId string                 `protobuf:"bytes,1,opt,name=compiled_model_id,json=compiledModelId,proto3" json:"compiled_model_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CompileModelResponse) Reset() {
	*x = CompileModelResponse{}
	mi := &file_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileModelResponse) ProtoMessage() {}

func (x *CompileModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileModelResponse.ProtoReflect.Descriptor instead.
func (*CompileModelResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{3}
}

func (x *CompileModelResponse) GetCompiledModelId() string {
	if x != nil {
		return x.CompiledModelId
	}
	return ""
}

type GetCompileStatusRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CompiledModelId string                 `protobuf:"bytes,1,opt,name=compiled_model_id,json=compiledModelId,proto3" json:"compiled_model_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetCompileStatusRequest) Reset() {
	*x = GetCompileStatusRequest{}
	mi := &file_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompileStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompileStatusRequest) ProtoMessage() {}

func (x *GetCompileStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompileStatusRequest.ProtoReflect.Descriptor instead.
func (*GetCompileStatusRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{4}
}

func (x *GetCompileStatusRequest) GetCompiledModelId() string {
	if x != nil {
		return x.CompiledModelId
	}
	return ""
}

type GetCompileStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	PlanId        string                 `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompileStatusResponse) Reset() {
	*x = GetCompileStatusResponse{}
	mi := &file_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompileStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompileStatusResponse) ProtoMessage() {}

func (x *GetCompileStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompileStatusResponse.ProtoReflect.Descriptor instead.
func (*GetCompileStatusResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{5}
}

func (x *GetCompileStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetCompileStatusResponse) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *GetCompileStatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_control_proto protoreflect.FileDescriptor

const file_control_proto_rawDesc = "" +
	"\n" +
	"\rcontrol.proto\x12\acontrol\"\x9a\x01\n" +
	"\x14RegisterModelRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12#\n" +
	"\rmodel_content\x18\x03 \x01(\fR\fmodelContent\x12!\n" +
	"\flibrary_type\x18\x04 \x01(\tR\vlibraryType\"2\n" +
	"\x15RegisterModelResponse\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\"J\n" +
	"\x13CompileModelRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x18\n" +
	"\aprofile\x18\x02 \x01(\tR\aprofile\"B\n" +
	"\x14CompileModelResponse\x12*\n" +
	"\x11compiled_model_id\x18\x01 \x01(\tR\x0fcompiledModelId\"E\n" +
	"\x17GetCompileStatusRequest\x12*\n" +
	"\x11compiled_model_id\x18\x01 \x01(\tR\x0fcompiledModelId\"p\n" +
	"\x18GetCompileStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage2\x86\x02\n" +
	"\x0eControlService\x12N\n" +
	"\rRegisterModel\x12\x1d.control.RegisterModelRequest\x1a\x1e.control.RegisterModelResponse\x12K\n" +
	"\fCompileModel\x12\x1c.control.CompileModelRequest\x1a\x1d.control.CompileModelResponse\x12W\n" +
	"\x10GetCompileStatus\x12 .control.GetCompileStatusRequest\x1a!.control.GetCompileStatusResponseB+Z)github.com/fhe-gbdt-serving/proto/controlb\x06proto3"

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData []byte
)

func file_control_proto_rawDescGZIP() []byte {
	file_control_proto_rawDescOnce.Do(func() {
		file_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)))
	})
	return file_control_proto_rawDescData
}

var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_control_proto_goTypes = []any{
	(*RegisterModelRequest)(nil),     // 0: control.RegisterModelRequest
	(*RegisterModelResponse)(nil),    // 1: control.RegisterModelResponse
	(*CompileModelRequest)(nil),      // 2: control.CompileModelRequest
	(*CompileModelResponse)(nil),     // 3: control.CompileModelResponse
	(*GetCompileStatusRequest)(nil),  // 4: control.GetCompileStatusRequest
	(*GetCompileStatusResponse)(nil), // 5: control.GetCompileStatusResponse
}
var file_control_proto_depIdxs = []int32{
	0, // 0: control.ControlService.RegisterModel:input_type -> control.RegisterModelRequest
	2, // 1: control.ControlService.CompileModel:input_type -> control.CompileModelRequest
	4, // 2: control.ControlService.GetCompileStatus:input_type -> control.GetCompileStatusRequest
	1, // 3: control.ControlService.RegisterModel:output_type -> control.RegisterModelResponse
	3, // 4: control.ControlService.CompileModel:output_type -> control.CompileModelResponse
	5, // 5: control.ControlService.GetCompileStatus:output_type -> control.GetCompileStatusResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_control_proto_init() }
func file_control_proto_init() {
	if File_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_proto_goTypes,
		DependencyIndexes: file_control_proto_depIdxs,
		MessageInfos:      file_control_proto_msgTypes,
	}.Build()
	File_control_proto = out.File
	file_control_proto_goTypes = nil
	file_control_proto_depIdxs = nil
}
