// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: inference.proto

package inference

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PredictRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TenantId        string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CompiledModelId string                 `protobuf:"bytes,2,opt,name=compiled_model_id,json=compiledModelId,proto3" json:"compiled_model_id,omitempty"`
	Profile         string                 `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"` // latency | throughput
	Batch           *CiphertextBatch       `protobuf:"bytes,4,opt,name=batch,proto3" json:"batch,omitempty"`
	Meta            map[string]string      `protobuf:"bytes,5,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	mi := &file_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{0}
}

func (x *PredictRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *PredictRequest) GetCompiledModelId() string {
	if x != nil {
		return x.CompiledModelId
	}
	return ""
}

func (x *PredictRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *PredictRequest) GetBatch() *CiphertextBatch {
	if x != nil {
		return x.Batch
	}
	return nil
}

func (x *PredictRequest) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

type CiphertextBatch struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SchemeId        string                 `protobuf:"bytes,1,opt,name=scheme_id,json=schemeId,proto3" json:"scheme_id,omitempty"`
	BatchSize       uint32                 `protobuf:"varint,2,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	PackingLayoutId string                 `protobuf:"bytes,3,opt,name=packing_layout_id,json=packingLayoutId,proto3" json:"packing_layout_id,omitempty"`
	Payload         []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	FeatureNames    []string               `protobuf:"bytes,5,rep,name=feature_names,json=featureNames,proto3" json:"feature_names,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CiphertextBatch) Reset() {
	*x = CiphertextBatch{}
	mi := &file_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CiphertextBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CiphertextBatch) ProtoMessage() {}

func (x *CiphertextBatch) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CiphertextBatch.ProtoReflect.Descriptor instead.
func (*CiphertextBatch) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{1}
}

func (x *CiphertextBatch) GetSchemeId() string {
	if x != nil {
		return x.SchemeId
	}
	return ""
}

func (x *CiphertextBatch) GetBatchSize() uint32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *CiphertextBatch) GetPackingLayoutId() string {
	if x != nil {
		return x.PackingLayoutId
	}
	return ""
}

func (x *CiphertextBatch) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CiphertextBatch) GetFeatureNames() []string {
	if x != nil {
		return x.FeatureNames
	}
	return nil
}

type PredictResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outputs       *CiphertextBatch       `protobuf:"bytes,1,opt,name=outputs,proto3" json:"outputs,omitempty"`
	Stats         *RuntimeStats          `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictResponse) Reset() {
	*x = PredictResponse{}
	mi := &file_inference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictResponse) ProtoMessage() {}

func (x *PredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictResponse.ProtoReflect.Descriptor instead.
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{2}
}

func (x *PredictResponse) GetOutputs() *CiphertextBatch {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *PredictResponse) GetStats() *RuntimeStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type RuntimeStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Comparisons    uint64                 `protobuf:"varint,1,opt,name=comparisons,proto3" json:"comparisons,omitempty"`
	SchemeSwitches uint64                 `protobuf:"varint,2,opt,name=scheme_switches,json=schemeSwitches,proto3" json:"scheme_switches,omitempty"`
	Bootstraps     uint64                 `protobuf:"varint,3,opt,name=bootstraps,proto3" json:"bootstraps,omitempty"`
	Rotations      uint64                 `protobuf:"varint,4,opt,name=rotations,proto3" json:"rotations,omitempty"`
	RuntimeMs      float64                `protobuf:"fixed64,5,opt,name=runtime_ms,json=runtimeMs,proto3" json:"runtime_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RuntimeStats) Reset() {
	*x = RuntimeStats{}
	mi := &file_inference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeStats) ProtoMessage() {}

func (x *RuntimeStats) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeStats.ProtoReflect.Descriptor instead.
func (*RuntimeStats) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{3}
}

func (x *RuntimeStats) GetComparisons() uint64 {
	if x != nil {
		return x.Comparisons
	}
	return 0
}

func (x *RuntimeStats) GetSchemeSwitches() uint64 {
	if x != nil {
		return x.SchemeSwitches
	}
	return 0
}

func (x *RuntimeStats) GetBootstraps() uint64 {
	if x != nil {
		return x.Bootstraps
	}
	return 0
}

func (x *RuntimeStats) GetRotations() uint64 {
	if x != nil {
		return x.Rotations
	}
	return 0
}

func (x *RuntimeStats) GetRuntimeMs() float64 {
	if x != nil {
		return x.RuntimeMs
	}
	return 0
}

var File_inference_proto protoreflect.FileDescriptor

const file_inference_proto_rawDesc = "" +
	"\n" +
	"\x0finference.proto\x12\tinference\"\x97\x02\n" +
	"\x0ePredictRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12*\n" +
	"\x11compiled_model_id\x18\x02 \x01(\tR\x0fcompiledModelId\x12\x18\n" +
	"\aprofile\x18\x03 \x01(\tR\aprofile\x120\n" +
	"\x05batch\x18\x04 \x01(\v2\x1a.inference.CiphertextBatchR\x05batch\x127\n" +
	"\x04meta\x18\x05 \x03(\v2#.inference.PredictRequest.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb8\x01\n" +
	"\x0fCiphertextBatch\x12\x1b\n" +
	"\tscheme_id\x18\x01 \x01(\tR\bschemeId\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x02 \x01(\rR\tbatchSize\x12*\n" +
	"\x11packing_layout_id\x18\x03 \x01(\tR\x0fpackingLayoutId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12#\n" +
	"\rfeature_names\x18\x05 \x03(\tR\ffeatureNames\"v\n" +
	"\x0fPredictResponse\x124\n" +
	"\aoutputs\x18\x01 \x01(\v2\x1a.inference.CiphertextBatchR\aoutputs\x12-\n" +
	"\x05stats\x18\x02 \x01(\v2\x17.inference.RuntimeStatsR\x05stats\"\xb6\x01\n" +
	"\fRuntimeStats\x12 \n" +
	"\vcomparisons\x18\x01 \x01(\x04R\vcomparisons\x12'\n" +
	"\x0fscheme_switches\x18\x02 \x01(\x04R\x0eschemeSwitches\x12\x1e\n" +
	"\n" +
	"bootstraps\x18\x03 \x01(\x04R\n" +
	"bootstraps\x12\x1c\n" +
	"\trotations\x18\x04 \x01(\x04R\trotations\x12\x1d\n" +
	"\n" +
	"runtime_ms\x18\x05 \x01(\x01R\truntimeMs2T\n" +
	"\x10InferenceService\x12@\n" +
	"\aPredict\x12\x19.inference.PredictRequest\x1a\x1a.inference.PredictResponseB-Z+github.com/fhe-gbdt-serving/proto/inferenceb\x06proto3"

var (
	file_inference_proto_rawDescOnce sync.Once
	file_inference_proto_rawDescData []byte
)

func file_inference_proto_rawDescGZIP() []byte {
	file_inference_proto_rawDescOnce.Do(func() {
		file_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inference_proto_rawDesc), len(file_inference_proto_rawDesc)))
	})
	return file_inference_proto_rawDescData
}

var file_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_inference_proto_goTypes = []any{
	(*PredictRequest)(nil),  // 0: inference.PredictRequest
	(*CiphertextBatch)(nil), // 1: inference.CiphertextBatch
	(*PredictResponse)(nil), // 2: inference.PredictResponse
	(*RuntimeStats)(nil),    // 3: inference.RuntimeStats
	nil,                     // 4: inference.PredictRequest.MetaEntry
}
var file_inference_proto_depIdxs = []int32{
	1, // 0: inference.PredictRequest.batch:type_name -> inference.CiphertextBatch
	4, // 1: inference.PredictRequest.meta:type_name -> inference.PredictRequest.MetaEntry
	1, // 2: inference.PredictResponse.outputs:type_name -> inference.CiphertextBatch
	3, // 3: inference.PredictResponse.stats:type_name -> inference.RuntimeStats
	0, // 4: inference.InferenceService.Predict:input_type -> inference.PredictRequest
	2, // 5: inference.InferenceService.Predict:output_type -> inference.PredictResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_inference_proto_init() }
func file_inference_proto_init() {
	if File_inference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inference_proto_rawDesc), len(file_inference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inference_proto_goTypes,
		DependencyIndexes: file_inference_proto_depIdxs,
		MessageInfos:      file_inference_proto_msgTypes,
	}.Build()
	File_inference_proto = out.File
	file_inference_proto_goTypes = nil
	file_inference_proto_depIdxs = nil
}
